<?php

/**
 * @file
 * Contains kanban_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kanban_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kanban_core module.
    case 'help.page.kanban_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides tables, columns and tasks entities to the application.') . '</p>';
      return $output;

    default:
  }
}
